// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sanchitdeora/PokeSim/usermanagement (interfaces: UserManager)

// Package mock_user_manager is a generated GoMock package.
package mock_user_manager

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/sanchitdeora/PokeSim/data"
)

// MockUserManager is a mock of UserManager interface.
type MockUserManager struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagerMockRecorder
}

// MockUserManagerMockRecorder is the mock recorder for MockUserManager.
type MockUserManagerMockRecorder struct {
	mock *MockUserManager
}

// NewMockUserManager creates a new mock instance.
func NewMockUserManager(ctrl *gomock.Controller) *MockUserManager {
	mock := &MockUserManager{ctrl: ctrl}
	mock.recorder = &MockUserManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManager) EXPECT() *MockUserManagerMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUserManager) GetUser() *data.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser")
	ret0, _ := ret[0].(*data.User)
	return ret0
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserManagerMockRecorder) GetUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserManager)(nil).GetUser))
}

// PostBattleUpdate mocks base method.
func (m *MockUserManager) PostBattleUpdate(arg0 *data.User, arg1 *data.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostBattleUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostBattleUpdate indicates an expected call of PostBattleUpdate.
func (mr *MockUserManagerMockRecorder) PostBattleUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostBattleUpdate", reflect.TypeOf((*MockUserManager)(nil).PostBattleUpdate), arg0, arg1)
}

// PostWildUpdate mocks base method.
func (m *MockUserManager) PostWildUpdate(arg0 *data.User, arg1 bool, arg2 *data.Pokemon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostWildUpdate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostWildUpdate indicates an expected call of PostWildUpdate.
func (mr *MockUserManagerMockRecorder) PostWildUpdate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostWildUpdate", reflect.TypeOf((*MockUserManager)(nil).PostWildUpdate), arg0, arg1, arg2)
}

// SaveUser mocks base method.
func (m *MockUserManager) SaveUser() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser")
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserManagerMockRecorder) SaveUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserManager)(nil).SaveUser))
}

// StatUpdate mocks base method.
func (m *MockUserManager) StatUpdate(arg0 data.Result) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StatUpdate", arg0)
}

// StatUpdate indicates an expected call of StatUpdate.
func (mr *MockUserManagerMockRecorder) StatUpdate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatUpdate", reflect.TypeOf((*MockUserManager)(nil).StatUpdate), arg0)
}
