// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sanchitdeora/PokeSim/pokemon (interfaces: LevelUp)

// Package mock_pokemon is a generated GoMock package.
package mock_pokemon

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/sanchitdeora/PokeSim/data"
)

// MockLevelUp is a mock of LevelUp interface.
type MockLevelUp struct {
	ctrl     *gomock.Controller
	recorder *MockLevelUpMockRecorder
}

// MockLevelUpMockRecorder is the mock recorder for MockLevelUp.
type MockLevelUpMockRecorder struct {
	mock *MockLevelUp
}

// NewMockLevelUp creates a new mock instance.
func NewMockLevelUp(ctrl *gomock.Controller) *MockLevelUp {
	mock := &MockLevelUp{ctrl: ctrl}
	mock.recorder = &MockLevelUpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLevelUp) EXPECT() *MockLevelUpMockRecorder {
	return m.recorder
}

// ReceiveResponse mocks base method.
func (m *MockLevelUp) ReceiveResponse() data.LevelUpEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveResponse")
	ret0, _ := ret[0].(data.LevelUpEvent)
	return ret0
}

// ReceiveResponse indicates an expected call of ReceiveResponse.
func (mr *MockLevelUpMockRecorder) ReceiveResponse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveResponse", reflect.TypeOf((*MockLevelUp)(nil).ReceiveResponse))
}

// SendEvent mocks base method.
func (m *MockLevelUp) SendEvent(arg0 data.LevelUpEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEvent", arg0)
}

// SendEvent indicates an expected call of SendEvent.
func (mr *MockLevelUpMockRecorder) SendEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEvent", reflect.TypeOf((*MockLevelUp)(nil).SendEvent), arg0)
}
