// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sanchitdeora/PokeSim/pokemon (interfaces: PokemonManager)

// Package mock_pokemon_manager is a generated GoMock package.
package mock_pokemon_manager

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/sanchitdeora/PokeSim/data"
)

// MockPokemonManager is a mock of PokemonManager interface.
type MockPokemonManager struct {
	ctrl     *gomock.Controller
	recorder *MockPokemonManagerMockRecorder
}

// MockPokemonManagerMockRecorder is the mock recorder for MockPokemonManager.
type MockPokemonManagerMockRecorder struct {
	mock *MockPokemonManager
}

// NewMockPokemonManager creates a new mock instance.
func NewMockPokemonManager(ctrl *gomock.Controller) *MockPokemonManager {
	mock := &MockPokemonManager{ctrl: ctrl}
	mock.recorder = &MockPokemonManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPokemonManager) EXPECT() *MockPokemonManagerMockRecorder {
	return m.recorder
}

// EvGain mocks base method.
func (m *MockPokemonManager) EvGain(arg0 *data.Pokemon, arg1 data.PokemonStats) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EvGain", arg0, arg1)
}

// EvGain indicates an expected call of EvGain.
func (mr *MockPokemonManagerMockRecorder) EvGain(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvGain", reflect.TypeOf((*MockPokemonManager)(nil).EvGain), arg0, arg1)
}

// Evolve mocks base method.
func (m *MockPokemonManager) Evolve(arg0 *data.Pokemon) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Evolve", arg0)
}

// Evolve indicates an expected call of Evolve.
func (mr *MockPokemonManagerMockRecorder) Evolve(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evolve", reflect.TypeOf((*MockPokemonManager)(nil).Evolve), arg0)
}

// ExperienceGain mocks base method.
func (m *MockPokemonManager) ExperienceGain(arg0 *data.Pokemon, arg1 data.Pokemon) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExperienceGain", arg0, arg1)
}

// ExperienceGain indicates an expected call of ExperienceGain.
func (mr *MockPokemonManagerMockRecorder) ExperienceGain(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExperienceGain", reflect.TypeOf((*MockPokemonManager)(nil).ExperienceGain), arg0, arg1)
}

// LearnNewMoves mocks base method.
func (m *MockPokemonManager) LearnNewMoves(arg0 *data.Moves) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LearnNewMoves", arg0)
}

// LearnNewMoves indicates an expected call of LearnNewMoves.
func (mr *MockPokemonManagerMockRecorder) LearnNewMoves(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LearnNewMoves", reflect.TypeOf((*MockPokemonManager)(nil).LearnNewMoves), arg0)
}
