// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sanchitdeora/PokeSim/pokemon (interfaces: PokemonService)

// Package mock_pokemon_service is a generated GoMock package.
package mock_pokemon_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/sanchitdeora/PokeSim/data"
)

// MockPokemonService is a mock of PokemonService interface.
type MockPokemonService struct {
	ctrl     *gomock.Controller
	recorder *MockPokemonServiceMockRecorder
}

// MockPokemonServiceMockRecorder is the mock recorder for MockPokemonService.
type MockPokemonServiceMockRecorder struct {
	mock *MockPokemonService
}

// NewMockPokemonService creates a new mock instance.
func NewMockPokemonService(ctrl *gomock.Controller) *MockPokemonService {
	mock := &MockPokemonService{ctrl: ctrl}
	mock.recorder = &MockPokemonServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPokemonService) EXPECT() *MockPokemonServiceMockRecorder {
	return m.recorder
}

// EvGain mocks base method.
func (m *MockPokemonService) EvGain(arg0 *data.Pokemon, arg1 data.PokemonStats) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EvGain", arg0, arg1)
}

// EvGain indicates an expected call of EvGain.
func (mr *MockPokemonServiceMockRecorder) EvGain(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvGain", reflect.TypeOf((*MockPokemonService)(nil).EvGain), arg0, arg1)
}

// Evolve mocks base method.
func (m *MockPokemonService) Evolve(arg0 *data.Pokemon) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Evolve", arg0)
}

// Evolve indicates an expected call of Evolve.
func (mr *MockPokemonServiceMockRecorder) Evolve(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evolve", reflect.TypeOf((*MockPokemonService)(nil).Evolve), arg0)
}

// ExperienceGain mocks base method.
func (m *MockPokemonService) ExperienceGain(arg0 *data.Pokemon, arg1 data.Pokemon) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExperienceGain", arg0, arg1)
}

// ExperienceGain indicates an expected call of ExperienceGain.
func (mr *MockPokemonServiceMockRecorder) ExperienceGain(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExperienceGain", reflect.TypeOf((*MockPokemonService)(nil).ExperienceGain), arg0, arg1)
}

// GetExperienceRequiredForNextLevel mocks base method.
func (m *MockPokemonService) GetExperienceRequiredForNextLevel(arg0 *data.Pokemon) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExperienceRequiredForNextLevel", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetExperienceRequiredForNextLevel indicates an expected call of GetExperienceRequiredForNextLevel.
func (mr *MockPokemonServiceMockRecorder) GetExperienceRequiredForNextLevel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExperienceRequiredForNextLevel", reflect.TypeOf((*MockPokemonService)(nil).GetExperienceRequiredForNextLevel), arg0)
}

// LearnNewMoves mocks base method.
func (m *MockPokemonService) LearnNewMoves(arg0 *data.Moves) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LearnNewMoves", arg0)
}

// LearnNewMoves indicates an expected call of LearnNewMoves.
func (mr *MockPokemonServiceMockRecorder) LearnNewMoves(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LearnNewMoves", reflect.TypeOf((*MockPokemonService)(nil).LearnNewMoves), arg0)
}
