// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sanchitdeora/PokeSim/gamestate (interfaces: GameStateManager)

// Package mock_game_state_manager is a generated GoMock package.
package mock_game_state_manager

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gamestate "github.com/sanchitdeora/PokeSim/gamestate"
)

// MockGameStateManager is a mock of GameStateManager interface.
type MockGameStateManager struct {
	ctrl     *gomock.Controller
	recorder *MockGameStateManagerMockRecorder
}

// MockGameStateManagerMockRecorder is the mock recorder for MockGameStateManager.
type MockGameStateManagerMockRecorder struct {
	mock *MockGameStateManager
}

// NewMockGameStateManager creates a new mock instance.
func NewMockGameStateManager(ctrl *gomock.Controller) *MockGameStateManager {
	mock := &MockGameStateManager{ctrl: ctrl}
	mock.recorder = &MockGameStateManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameStateManager) EXPECT() *MockGameStateManagerMockRecorder {
	return m.recorder
}

// AddTrainerProgress mocks base method.
func (m *MockGameStateManager) AddTrainerProgress(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTrainerProgress", arg0)
}

// AddTrainerProgress indicates an expected call of AddTrainerProgress.
func (mr *MockGameStateManagerMockRecorder) AddTrainerProgress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrainerProgress", reflect.TypeOf((*MockGameStateManager)(nil).AddTrainerProgress), arg0)
}

// Get mocks base method.
func (m *MockGameStateManager) Get() *gamestate.GameState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*gamestate.GameState)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockGameStateManagerMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGameStateManager)(nil).Get))
}

// Load mocks base method.
func (m *MockGameStateManager) Load() (*gamestate.GameState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*gamestate.GameState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockGameStateManagerMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockGameStateManager)(nil).Load))
}

// Save mocks base method.
func (m *MockGameStateManager) Save() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save")
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGameStateManagerMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGameStateManager)(nil).Save))
}
